
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.j3d.ImageComponent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adi
 */
public class ViewFrame extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet rs;
    /**
     * Creates new form ViewFrame
     */
    public ViewFrame(String ID) throws IOException {
        initComponents();
        show_element(ID);
    }
    public void show_element(String id) throws IOException{
        System.out.println("show elements");
        String[] split = id.split(" ");
        String sql = "SELECT * FROM ADY.PERSON where NAME='" + split[0] +"'and SURNAME='" + split[1] +"'";
        System.out.println(sql);
        try{
            String host = "jdbc:derby://localhost:1527/Employees";
            String userName = "ady";
            String password = "adrian";
            conn = DriverManager.getConnection(host,userName,password);
        }
        catch (SQLException err){
            System.out.println(err.getMessage());
        }
        try{
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                String name = rs.getString("NAME");
                String surname = rs.getString("Surname");
                String country = rs.getString("COUNTRY");
                String county = rs.getString("COUNTY");
                String town = rs.getString("TOWN");
                String street = rs.getString("STREET");
                String number = rs.getString("NUMBER");
                String building = rs.getString("BUILDING");
                String series = rs.getString("SERIES");
                String flat = rs.getString("FLAT");
                String idNumber = rs.getString("ID_NUMBER");
                String drivingLicense = rs.getString("DRIVING_LICENSE");
                String qualificationCard = rs.getString("QUALIFICATION_CARD");
                String pic = rs.getString("PICTURE");
                dbName.setText(name);
                dbSurname.setText(surname);
                dbCountry.setText(country);
                dbCounty.setText(county);
                dbTown.setText(town);
                dbStreet.setText(street);
                dbNumber.setText(number);
                dbBuilding.setText(building);
                dbSeries.setText(series);
                dbFlat.setText(flat);
                dbIdCard.setText(idNumber);
                dbDrivingLicense.setText(drivingLicense);
                dbQualificationCard.setText(qualificationCard);
                BufferedImage image = new BufferedImage(100,100,BufferedImage.TYPE_INT_RGB);
                image = ImageIO.read(new File(pic));
                
                jLabel1.setIcon(new ImageIcon(image));
                jLabel1.setBounds(10, 10, 10, 10);
                
                
            }
            //System.out.println(rs.getString("NAME"));
        }
        catch(SQLException err){
            System.out.println(err.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblCounty = new javax.swing.JLabel();
        lblTown = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblBuilding = new javax.swing.JLabel();
        lblSeries = new javax.swing.JLabel();
        lblFlat = new javax.swing.JLabel();
        lblIdCard = new javax.swing.JLabel();
        lblDrivingLicense = new javax.swing.JLabel();
        lblQualificationCard = new javax.swing.JLabel();
        dbName = new javax.swing.JLabel();
        dbSurname = new javax.swing.JLabel();
        dbCountry = new javax.swing.JLabel();
        dbCounty = new javax.swing.JLabel();
        dbTown = new javax.swing.JLabel();
        dbStreet = new javax.swing.JLabel();
        dbNumber = new javax.swing.JLabel();
        dbBuilding = new javax.swing.JLabel();
        dbSeries = new javax.swing.JLabel();
        dbFlat = new javax.swing.JLabel();
        dbIdCard = new javax.swing.JLabel();
        dbDrivingLicense = new javax.swing.JLabel();
        dbQualificationCard = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        lblName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblName.setText("Name:");

        lblSurname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblSurname.setText("Surname:");

        lblCountry.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblCountry.setText("Country:");

        lblCounty.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblCounty.setText("County:");

        lblTown.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTown.setText("Town:");

        lblStreet.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblStreet.setText("Street:");

        lblNumber.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNumber.setText("Number:");

        lblBuilding.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblBuilding.setText("Building:");

        lblSeries.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblSeries.setText("Series:");

        lblFlat.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblFlat.setText("Flat:");

        lblIdCard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblIdCard.setText("ID card:");

        lblDrivingLicense.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblDrivingLicense.setText("Driving license:");

        lblQualificationCard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblQualificationCard.setText("Qualification card:");

        dbName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbName.setPreferredSize(new java.awt.Dimension(140, 21));

        dbSurname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbSurname.setPreferredSize(new java.awt.Dimension(140, 21));

        dbCountry.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbCountry.setPreferredSize(new java.awt.Dimension(140, 21));

        dbCounty.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbCounty.setPreferredSize(new java.awt.Dimension(140, 21));

        dbTown.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbTown.setPreferredSize(new java.awt.Dimension(140, 21));

        dbStreet.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbStreet.setPreferredSize(new java.awt.Dimension(140, 21));

        dbNumber.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbNumber.setPreferredSize(new java.awt.Dimension(140, 21));

        dbBuilding.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbBuilding.setPreferredSize(new java.awt.Dimension(140, 21));

        dbSeries.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbSeries.setPreferredSize(new java.awt.Dimension(140, 21));

        dbFlat.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbFlat.setPreferredSize(new java.awt.Dimension(140, 21));

        dbIdCard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbIdCard.setPreferredSize(new java.awt.Dimension(140, 21));

        dbDrivingLicense.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbDrivingLicense.setPreferredSize(new java.awt.Dimension(140, 21));

        dbQualificationCard.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        dbQualificationCard.setPreferredSize(new java.awt.Dimension(140, 21));

        lblPicture.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPicture.setText("Picture:");

        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStreet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dbStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTown)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dbTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblCounty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dbCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumber)
                                        .addComponent(lblBuilding)
                                        .addComponent(lblSeries)
                                        .addComponent(lblFlat)
                                        .addComponent(lblIdCard)
                                        .addComponent(lblDrivingLicense)
                                        .addComponent(lblQualificationCard))
                                    .addGap(215, 215, 215)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dbSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbFlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbDrivingLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dbQualificationCard, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblSurname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPicture)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblCountry))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblPicture))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dbCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSurname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCountry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCounty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dbNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbFlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbDrivingLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbQualificationCard, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBuilding)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSeries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFlat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdCard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDrivingLicense)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQualificationCard)))))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewFrame("0").setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ViewFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbBuilding;
    private javax.swing.JLabel dbCountry;
    private javax.swing.JLabel dbCounty;
    private javax.swing.JLabel dbDrivingLicense;
    private javax.swing.JLabel dbFlat;
    private javax.swing.JLabel dbIdCard;
    private javax.swing.JLabel dbName;
    private javax.swing.JLabel dbNumber;
    private javax.swing.JLabel dbQualificationCard;
    private javax.swing.JLabel dbSeries;
    private javax.swing.JLabel dbStreet;
    private javax.swing.JLabel dbSurname;
    private javax.swing.JLabel dbTown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBuilding;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCounty;
    private javax.swing.JLabel lblDrivingLicense;
    private javax.swing.JLabel lblFlat;
    private javax.swing.JLabel lblIdCard;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblQualificationCard;
    private javax.swing.JLabel lblSeries;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTown;
    // End of variables declaration//GEN-END:variables
}
